### ISSUE TITLE
Add functionality for Creating and Removing rooms

### ISSUE THREAD

**Issue by Andrew-Gallimore** [Andrew-Gallimore/VDO.ninja-wrapper#6]
### Subtasks:
- [ ] Get input of director ID from URL
- [ ] Add functionality to the UI buttons
- [ ] Manage removing the rooms

**Comment by Andrew-Gallimore** [comment]
I am now taking on this feature, just so y'all know :D
