### ISSUE TITLE
Add functionality to Guest Control buttons

### ISSUE THREAD

**Issue by Andrew-Gallimore** [Andrew-Gallimore/VDO.ninja-wrapper#7]
### Description:
Making the buttons around a person's video actually function. Because right now they just sit there and look pretty, and I have made a mock up already for the button functionality. Just need to refactor that code and hook it up. :D

### Subtasks:
- [ ] Manage direct chat messages (needs direct chat in the first place though)
- [ ] Create solo audio option (need the director video/audio pannel)
- [ ] Need to figure out how to display the solo-audio option, popup modal?
- [ ] Manage groups integration
- [ ] Add transfer and Kick functionality
- [ ] Connect-up Mute audio and hide video options
- [ ] Rename capability directly on the person?
