### ISSUE TITLE
Create Director personal Video & Audio control panel

### ISSUE THREAD

**Issue by Andrew-Gallimore** [Andrew-Gallimore/VDO.ninja-wrapper#9]
### Subtasks:
- [ ] Need to add UI and camera/mic preview
- [ ] Need to figure out the position on the page and how to open it
- [ ] Need to link up the video/mic option lists to my page from Iframe
- [ ] Need to figure out how to switch video between rooms smoothly on front end and back end
